### ISSUE TITLE
Travis: check binaries of v0.12.0 from deploy service

### ISSUE THREAD

**Issue by cchampet** [tuttleofx/TuttleOFX#441]
Linux
```
locate libicuuc.so.48
locate libicui18n.so.48
```
Mac OS X
check dependencies

Add platform name to name of binaries.

**Comment by cchampet** [comment]
Need to check binaries on OSX.

**Comment by cchampet** [comment]
Error:
```bash
./bin/sam
```
Traceback (most recent call last):
  File "./bin/sam", line 11, in <module>
    from common import samUtils
  File "/Users/cchampet/Downloads/install-tuttle/bin/python/sam/common/samUtils.py", line 12, in <module>
    from pySequenceParser import sequenceParser
  File "/Library/Python/2.7/site-packages/pySequenceParser/sequenceParser.py", line 32, in <module>
    _sequenceParser = swig_import_helper()
  File "/Library/Python/2.7/site-packages/pySequenceParser/sequenceParser.py", line 28, in swig_import_helper
    _mod = imp.load_module('_sequenceParser', fp, pathname, description)
ImportError: dlopen(/Library/Python/2.7/site-packages/pySequenceParser/_sequenceParser.so, 2): Library not loaded: /opt/local/lib/libboost_regex-mt.dylib
  Referenced from: /Library/Python/2.7/site-packages/pySequenceParser/_sequenceParser.so
  Reason: image not found

**Comment by cchampet** [comment]
Linux opensuse 12.1:
__libicudata.so.48__ is missing.

**Comment by cchampet** [comment]
Checkout PR #466

**Comment by cchampet** [comment]
v0.12.1 binaries:
* Remove clang build (no tests run on Travis CI).
* ubuntu-gcc: problem with Viewer plugin  
OFX/Viewer-1.0.ofx.bundle/Contents/Linux-x86-64/Viewer-1.0.ofx: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /datas/cnt/apps/install-tuttle/OFX/Viewer-1.0.ofx.bundle/Contents/Linux-x86-64/../../../../lib/libglut.so.3)

**Comment by cchampet** [comment]
See commit 2672825

**Comment by cchampet** [comment]
Binaries built with python2.7 and python3.2 available since release 0.12.2:
https://github.com/tuttleofx/TuttleOFX/releases/tag/v0.12.2
