### ISSUE TITLE
clint default version on ubuntu

### ISSUE THREAD

**Issue by julietteTaka** [tuttleofx/TuttleOFX#457]
```
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 76, in <module>
    tools = getBestSamTools()
  File "/usr/local/bin/sam", line 54, in getBestSamTools
    return getSpecificSamTool(cmdLine[1])
  File "/usr/local/bin/sam", line 35, in getSpecificSamTool
    return {toolCommand: toolClass()}
  File "/usr/local/bin/python/sam/sam_do.py", line 73, in __init__
    '''+colored.blue('Processing options', bold=True)+'''
TypeError: blue() got an unexpected keyword argument 'bold'
```

The default version of clint on ubuntu is a bit old and has no bold argument.

**Comment by cchampet** [comment]
As the [USAGE.md](https://github.com/tuttleofx/TuttleOFX/blob/develop/USAGE.md) suggests, the clint version should be v0.4.1
What is the default clint version on your Ubuntu (12.04?) ?

**Comment by fabiencastan** [comment]
0.3.2 on ubuntu 14.04.
