### ISSUE TITLE
[sam] disable colors

### ISSUE THREAD

**Issue by fabiencastan** [tuttleofx/TuttleOFX#572]
`> sam do rawreader -h`
Gives an error on a color code:

```
...
    exposure                       : Double        1    [0     --> 10   ]
      Exposure shift in linear scale. Usable range from 0.25 (2-stop darken) to 8.0 (3-stop lighter). Default: 1.0 (no exposure shift).
    exposurePreserve               : Double        0    [0     --> 1    ]
      Parameter for noise reduction through wavelet denoising.
    whiteBalance                   : Choice    
                                            auto                           
                                            camera                         
                                            manual                         
      Select white balance mode.
    manualWhiteBalance            : Double        0    [1000  --> 40000]
--- Logging error ---
Traceback (most recent call last):
  File "/home/fab/dev/TuttleOFX/build_release_py3.4.3/install/bin/python/sam/sam_do.py", line 520, in run
    graphsWithNodes.append(self._getTuttleGraph(splitCmdGraph))
  File "/home/fab/dev/TuttleOFX/build_release_py3.4.3/install/bin/python/sam/sam_do.py", line 429, in _getTuttleGraph
    self._displayNodeHelp(nodeFullName, node)
  File "/home/fab/dev/TuttleOFX/build_release_py3.4.3/install/bin/python/sam/sam_do.py", line 367, in _displayNodeHelp
    self._displayParamHelp(param)
  File "/home/fab/dev/TuttleOFX/build_release_py3.4.3/install/bin/python/sam/sam_do.py", line 316, in _displayParamHelp
    puts(paramHint)
  File "/usr/local/lib/python3.4/dist-packages/clint/textui/core.py", line 68, in puts
    stream(_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 154: ordinal not in range(128)
```

And there is no way to disable it with an option or an environment variable.

**Comment by fabiencastan** [comment]
I don't have the problem with the latest version.
But it could still be good to have an option to disable colors.

**Comment by cchampet** [comment]
Already fixed :)
